### ISSUE TITLE
readme.md not found

### ISSUE THREAD

**Issue by Plasmatree** [lightingghost/sifreader#5]
Hi,

this tool sounds really useful, but unfortunately I can't install it via pip.
 
I get:
`Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "C:\Users\FLORIA~1\AppData\Local\Temp\pip-install-ttr95c0m\sifreader\setup.py", line 13, in <module>
long_description = open('readme.md').read(),
FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'
Command "python setup.py egg_info" failed with error code 1 in C:\Users\FLORIA~1\AppData\Local\Temp\pip-install-ttr95c0m\sifreader\
`
on Python 3.6.5

Seems similar to https://github.com/lightingghost/sifreader/issues/3

Upgrading setup tools didn't help.
Any idea?

Thanks for your effort,
Flo

**Comment by lightingghost** [comment]
Can you please try install from git?

```bash
git clone https://github.com/lightingghost/sifreader
cd sifreader
python setup.py install
```

There seems to be an issue with the current version of `setuptools` I am using.

**Comment by gabiossa** [comment]
It does not work for me, then appears: 'Permission denied'
